// Static configuration for fixed trade pairs universe
export const FIXED_TRADE_PAIRS = [
  "BTCUSDT", "ETHUSDT", "SOLUSDT", "XRPUSDT", "DOGEUSDT", "BNBUSDT", "ADAUSDT", "SUIUSDT", "TRXUSDT", "AVAXUSDT",
  "HYPEUSDT", "LINKUSDT", "LTCUSDT", "BCHUSDT", "PEPEUSDT", "WIFUSDT", "ENAUSDT", "NEARUSDT", "XLMUSDT", "DOTUSDT",
  "AAVEUSDT", "INJUSDT", "ATOMUSDT", "ARBUSDT", "OPUSDT", "SEIUSDT", "FETUSDT", "RENDERUSDT", "TONUSDT", "UNIUSDT",
  "FILUSDT", "ICPUSDT", "JUPUSDT", "PENDLEUSDT", "APTUSDT", "TAOUSDT", "ETCUSDT", "VETUSDT", "ALGOUSDT", "THETAUSDT",
  "CRVUSDT", "SANDUSDT", "MANAUSDT", "GALAUSDT", "IMXUSDT", "FLOWUSDT", "EOSUSDT", "KASUSDT", "STXUSDT", "RUNEUSDT",
  "DYDXUSDT", "PYTHUSDT", "TIAUSDT", "EIGENUSDT", "STRKUSDT", "CELOUSDT", "ROSEUSDT", "KAVAUSDT", "CHZUSDT", "AXSUSDT",
  "FTMUSDT", "JASMYUSDT", "NOTUSDT", "POPCATUSDT", "BONKUSDT", "FLOKIUSDT", "BRETTUSDT", "TURBOUSDT", "MEMEUSDT",
  "PEOPLEUSDT", "GMTUSDT", "CFXUSDT", "ONDOUSDT", "ZRXUSDT", "ZILUSDT", "IOTXUSDT", "ONEUSDT", "HOTUSDT", "ANKRUSDT",
  "MASKUSDT", "AI16ZUSDT", "ACTUSDT", "OMUSDT", "TRUMPUSDT", "HMSTRUSDT", "CATIUSDT", "MEWUSDT", "BOMEUSDT", "NEOUSDT",
  "QTUMUSDT", "COMPUSDT", "SNXUSDT", "YFIUSDT", "LDOUSDT", "SUSHIUSDT", "CAKEUSDT", "DUSKUSDT", "WLDUSDT", "EGLDUSDT",
  "MINAUSDT"
];
